### ISSUE TITLE
 Q: For TYPO3 v9 we are aiming to remove this stumbling block ...

### ISSUE THREAD

**Issue by ehwg** [tritum/form_element_linked_checkbox#12]
Hi, thank's for the extension. Is there an update available for TYPO3 v9. Or do you have any hints, sample, docu on how it would be done best in v9?
Thanks Eckard.

**Comment by tritum** [comment]
Hi Eckard, the extension works with v9 (now). There is no better solution for v9 and v10. We are aiming to improve the situation for v11. I will release v2.0 of this extension within the next days. I've just merged a very useful feature.
