### ISSUE TITLE
Maybe feature - TYPO3 8

### ISSUE THREAD

**Issue by Teisi** [tritum/form_element_linked_checkbox#15]
Sers,

I have tested this version with TYPO3 version 8.7, it seems to work there too. ;)

**Comment by tritum** [comment]
@Teisi so you are saying the current version works with v8 as well and we could change the emconf to support v8? I am not sure but I think we've added the opportunity to use sprintf() in labels in v9. Did you check this specific feature?

**Comment by Teisi** [comment]
@tritum you mean line 85 in FormElementLinkResolverHook? (vsprintf? Why should this not work? It's a nativ PHP function...).

Or did you mean the translation viewhelper? This uses the native PHP function too...

Or what do you mean?

**Comment by tritum** [comment]
I am closing this very old issue. A lot has been done since then and some improvements in the field of character substitution have been done.
