### ISSUE TITLE
The labels are empty

### ISSUE THREAD

**Issue by typo3ua** [tritum/form_element_linked_checkbox#19]
I tested your extension and I have seen that the labels are empty...

![linked_checkbox_not_l](https://user-images.githubusercontent.com/638022/81504176-76227f00-92f0-11ea-8729-bb3bf571ee26.png)

... and element too...

![linked_checkbox_not_l_1](https://user-images.githubusercontent.com/638022/81504290-14aee000-92f1-11ea-98b0-2dfb17641da1.png)

... is it normal?

#### System
- PHP 7.2
- TYPO3 9.5.16

**Comment by akiessling** [comment]
I just had the same problem and found the issue.. If you extend EXT:form with multiple Yaml files, e.g. from different extensions, the arrays from e.g. additionalViewModelModules and translationFile are merged and not extended/appended -> i had another translation file with also index 20 -> mine won. 
Same happened to the additionalViewModelModules, where that entry got index 0 and was overwritten by my own modules :/ 
```
additionalViewModelModules:
  - 'TYPO3/CMS/FormElementLinkedCheckbox/Backend/FormEditor/ViewModel'
```

I highly recommend https://extensions.typo3.org/extension/yaml_browser/ to get a glimpse of the hard to debug result of the yaml merge magic.. Memo to self: never use "-", always set a key e.g. to the current timestamp.

**Comment by tritum** [comment]
@akiessling I am with you and think we should use the current timestamp for the following 3 inclusions:
* https://github.com/tritum/form_element_linked_checkbox/blob/master/Configuration/Yaml/FormSetup.yaml#L52
* https://github.com/tritum/form_element_linked_checkbox/blob/master/Configuration/Yaml/FormSetup.yaml#L55
* https://github.com/tritum/form_element_linked_checkbox/blob/master/Configuration/Yaml/FormSetupV10.yaml#L10

That would harden the whole setup and avoid the problems described. Right?

Thanks for your comment and cheers, Björn

**Comment by akiessling** [comment]
Hi Björn,

My comment must have been from T3 10.4. So if the Yaml merging did not change with 11.5 the fix should still work.

**Comment by Barakur** [comment]
To add to this: If you set an index for an entry of `additionalViewModelModules` but the file is imported in Yaml via `imports` the index gets replaced again bei `0` :/  
Seems to be an additional Bug in Symfony.

Another question: Will there be a release soon with a timestamp as index for the view models? We use several extensions that add custom form elements and they all overwrite each other (I'm adding bug reports to all of them at the moment).

**Comment by Barakur** [comment]
The imports Bug is a Typo3 Bug, see https://forge.typo3.org/issues/94729

**Comment by tritum** [comment]
I am closing here. If problems arise -> please open a new ticket.
