### ISSUE TITLE
Support multiple links

### ISSUE THREAD

**Issue by Konafets** [tritum/form_element_linked_checkbox#20]
Could you check to support multiple links so that this extension supports a string like: 
"I have read the %s and the %s", which renders later to "I have read the Terms Of Use and the Data Privacy Policy"?

The best way would be supporting an RTE for the label but this is not supported by the forms framework yet.

**Comment by eliashaeussler** [comment]
Hey @Konafets :wave:

I pushed a first version as #31. If you have time to test it, I'd be very happy :)

```bash
composer config repositories.form-element-linked-checkbox vcs https://github.com/eliashaeussler/form_element_linked_checkbox.git
composer require tritum/form-element-linked-checkbox:"dev-feature/additional-links@dev"
```
