### ISSUE TITLE
Label links shown as '%s' in mails

### ISSUE THREAD

**Issue by t3brightside** [tritum/form_element_linked_checkbox#23]
Great extension that is, thanks!
I guess there's no way to show linked text in emails?
Labels show up as 'My label %s' in e-mails.

**Comment by anderlk** [comment]
Same problem here.

**Comment by szytek** [comment]
It can be solved with custom form finisher like this:


class CustomLogicFinisher extends AbstractFinisher {

    protected function executeInternal()
    {
        $formRuntime = $this->finisherContext->getFormRuntime();

        /** @var GenericFormElement $checkbox */
        $checkbox = $formRuntime->getFormDefinition()->getElementByIdentifier('your-checkbox-identifier');

        if ($checkbox instanceof GenericFormElement){
            $checkbox->setLabel(sprintf($checkbox->getLabel(), $checkbox->getProperties()['linkText']));
        }
    }

}

**Comment by kkusche** [comment]
great! Thank you @SylwesterDev

**Comment by anderlk** [comment]
@SylwesterDev great solution. Thanks.

**Comment by iamwebrocker** [comment]
Hi,

can somebody give me a nudge how to get this to work? 
I *think* I have the custom finisher class right, and address it in my form_definition, but the label still shows as "blah %s" in the summary step and the emails sent.

in the form yaml:

```
TYPO3:
  CMS:
    Form:
      prototypes:
        standard:
          finishersDefinition:
            LinkedCheckBox:
              implementationClassName: 'MYVENDOR\my_ext\Domain\Finishers\LinkedCheckBox'
```

in `ext/my_ext/Classes/Domain/Finishers/LinkedCheckBox`:

```
	declare(strict_types = 1);
	namespace MYVENDOR\MyExt\Domain\Finishers;

	class LinkedCheckBox extends \TYPO3\CMS\Form\Domain\Finishers\AbstractFinisher {
		protected function executeInternal()
		{
			$formRuntime = $this->finisherContext->getFormRuntime();

			/** @var GenericFormElement $checkbox */
			$checkbox = $formRuntime->getFormDefinition()->getElementByIdentifier('dataprocessing_accepted');

			if ($checkbox instanceof GenericFormElement){
				$checkbox->setLabel(sprintf($checkbox->getLabel(), $checkbox->getProperties()['linkText']));
			}
		}
	}
```

in form_definition:

```
(...)
prototypeName: standard
finishers:
  -
    identifier: LinkedCheckBox
  -
   identifier: EmailToReceiver
   options:
     subject: Foo
(...)
```

in composer.json:

```
(...)
  "autoload": {
        "psr-4": {
            "MYVENDOR\\MyExt\\": "Classes/"
        }
    }
(...)
```

is there something else I'm missing?
Thanks

**Comment by eliashaeussler** [comment]
Hi together :wave:

You're totally right, the current hook only affects rendering in Frontend, thus character substitution is not processed after the form was submitted.

We can use the hook `$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['ext/form']['afterFormStateInitialized']` instead, which is always triggered from `FormRuntime::triggerAfterFormStateInitialized`. Can you try the following patch and tell me if this works for you? I'd provide a PR then.

```diff
diff --git a/Classes/Hooks/FormElementLinkResolverHook.php b/Classes/Hooks/FormElementLinkResolverHook.php
index b925e39..ac17e0e 100644
--- a/Classes/Hooks/FormElementLinkResolverHook.php
+++ b/Classes/Hooks/FormElementLinkResolverHook.php
@@ -20,6 +20,7 @@ use TYPO3\CMS\Core\Utility\GeneralUtility;
 use TYPO3\CMS\Form\Domain\Model\FormElements\GenericFormElement;
 use TYPO3\CMS\Form\Domain\Model\Renderable\RootRenderableInterface;
 use TYPO3\CMS\Form\Domain\Runtime\FormRuntime;
+use TYPO3\CMS\Form\Domain\Runtime\FormRuntime\Lifecycle\AfterFormStateInitializedInterface;
 use TYPO3\CMS\Form\Service\TranslationService;
 use TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer;
 
@@ -29,13 +30,22 @@ use TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer;
  * @author Elias Häußler <elias@haeussler.dev>
  * @license GPL-2.0-or-later
  */
-class FormElementLinkResolverHook
+class FormElementLinkResolverHook implements AfterFormStateInitializedInterface
 {
     /**
      * @var string Form element type to match
      */
     protected $type = 'LinkedCheckbox';
 
+    public function afterFormStateInitialized(FormRuntime $formRuntime): void
+    {
+        $elements = $formRuntime->getFormDefinition()->getElements();
+
+        foreach ($elements as $element) {
+            $this->beforeRendering($formRuntime, $element);
+        }
+    }
+
     /**
      * Resolve link in label of form elements with type LinkedCheckbox.
      *
@@ -174,4 +184,4 @@ class FormElementLinkResolverHook
         } while(strpos($filteredValue, '%%') !== false);
         return strpos($filteredValue, '%') !== false;
     }
-}
\ No newline at end of file
+}
diff --git a/ext_localconf.php b/ext_localconf.php
index b052f65..682ac39 100644
--- a/ext_localconf.php
+++ b/ext_localconf.php
@@ -32,4 +32,6 @@ call_user_func(function () {
 
     $GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['ext/form']['beforeRendering'][1571076908]
         = \TRITUM\FormElementLinkedCheckbox\Hooks\FormElementLinkResolverHook::class;
+    $GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['ext/form']['afterFormStateInitialized'][1632578835]
+        = \TRITUM\FormElementLinkedCheckbox\Hooks\FormElementLinkResolverHook::class;
 });
```

**Comment by iamwebrocker** [comment]
Hi @eliashaeussler,
 
can confirm that it now works and substitutes the %s. In my use case I now see the link's html markup in the text

![grafik](https://user-images.githubusercontent.com/1223080/135424489-30a411ea-a8b4-4875-9f6f-8d4addb5454a.png)

but this maybe due to the latest html sanitizer stuff that TYPO3 implemented recently, so I'll have a look into the mail and confirmation templates.

massive thank you for the fix.

**Comment by eliashaeussler** [comment]
Hi @iamwebrocker :wave:

> can confirm that it now works and substitutes the %s

Great :tada: I'll provide a PR then.

> In my use case I now see the link's html markup in the text in the confirmation and email (in the form it is displayed correctly as a clickable link)

Yeah, that's correct. We had the same thing in the form field partial itself and needed to use `f:format.raw`:

https://github.com/tritum/form_element_linked_checkbox/blob/acf3a430b37c6329833af305c011163ece04b45d/Resources/Private/Frontend/Partials/LinkedCheckbox.html#L14

I think that's totally okay from a core-perspective, because it's clearly a security issue to not escape HTML in this case. You might need to overwrite the finisher email templates and change them accordingly. Make sure to do `f:format.raw` only for elements with type `LinkedCheckbox`, e.g.:

```html
<f:if condition="{formValue.element.type} == 'LinkedCheckbox'">
  <f:then>
    <td colspan="2"><b>{formvh:translateElementProperty(element: formValue.element, property: 'label') -> f:format.raw()}</b></td>
  </f:then>
  <f:else>
    <td colspan="2"><b>{formvh:translateElementProperty(element: formValue.element, property: 'label')}</b></td>
  </f:else>
</f:if>
```

(taken from https://github.com/TYPO3/typo3/blob/d761fdebf4b04d613a5e91c20bdd97344d464920/typo3/sysext/form/Resources/Private/Frontend/Templates/Finishers/Email/Html.html#L15)

Let me know if that works for you.

**Comment by iamwebrocker** [comment]
@eliashaeussler 
do you happen to know which template is responsible for the "summary" step? this now is the last place that shows the escaped link (as seen in the screenshot above). everything else I was able to format.raw or stripTag where needed.
