### ISSUE TITLE
Linktext is missing in confirmation Mail

### ISSUE THREAD

**Issue by robinson2** [tritum/form_element_linked_checkbox#28]
The Linktext ist missing in the confirmation mail.

In my case it is "Ich akzeptiere Ihre" instead of "Ich akzeptiere Ihre Datenschutzerklärung".

**Comment by tritum** [comment]
IMHO the same as #23. Can you confirm @robinson2?

**Comment by robinson2** [comment]
I suppose yes

**Comment by tritum** [comment]
Thank you for your fast reply. Closing this issue. We'll continue in #23.
