### ISSUE TITLE
Extension key in composer.json

### ISSUE THREAD

**Issue by fritzdacat** [tritum/form_element_linked_checkbox#29]
The TYPO3 extension package "tritum/form-element-linked-checkbox", does not define an extension key in its composer.json. Please report this to the author of this package. Specifying the extension key will be mandatory in future versions of TYPO3 (see: https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/ComposerJson/Index.html#extra)

**Comment by tritum** [comment]
Thank you for your report. This has been fixed a while ago but was not officially released. I've just pushed version 2.1.2 which fixes this issue.
