### ISSUE TITLE
TYPO3 - 11 Support?

### ISSUE THREAD

**Issue by ingeniumdesign** [tritum/form_element_linked_checkbox#34]
Hi all,
an you update the Ext. for the TYPO3 11 ?

Thanks!

**Comment by tritum** [comment]
Hi @ingeniumdesign. I have merged an according PR and raised the requirements/ bumped the version of the extension. Can you please test if the current master works for you? Thanks!

**Comment by tritum** [comment]
Just released it everywhere (version 2.2.0) on packagist and TER.
