### ISSUE TITLE
Can't see the checkbox in the Frontend v10. 

### ISSUE THREAD

**Issue by Efdal90** [tritum/form_element_linked_checkbox#43]
Hi, I cant see this checkbox in the Frontend. In the preview mode I can see it. I have also cleared all Caches.
Is it not enough to install this addon to use it?

**Comment by tritum** [comment]
See https://github.com/tritum/form_element_linked_checkbox#install. Did you do all of the mentioned steps, especially this one:

> Add the static TypoScript configuration to your TypoScript template.

**Comment by Efdal90** [comment]
I installed this addon over the packagemanager in the typo3 backend. Should I do the metioned steps though?

**Comment by eliashaeussler** [comment]
Hi @Efdal90,

it doesn't matter what installation method you have chosen, however installation via Composer is recommended. In any case, you need to include the static TypoScript template (`EXT:form_element_linked_checkbox/Configuration/TypoScript`) to your root template.

**Comment by tritum** [comment]
Closing this issue since it is no problem of the extension.
