### ISSUE TITLE
feature request: linked text

### ISSUE THREAD

**Issue by bh-teufels** [tritum/form_element_linked_checkbox#48]
In some cases, the data protection officer recommends a reference with a link to the data protection declaration instead of a consent (checkbox). Here, the "linked text" type would be very helpful

**Comment by tritum** [comment]
@bh-teufels can you further elaborate what's needed here? Do you have an example at hand? Thanks.

**Comment by bh-teufels** [comment]
we currently  need two types of data protection hint 
- linked checkbox: [ ] lorem ipsum dolor [link to page](#)
and without the checkbox 
- linked text: lorem ipsum dolor [link to page](#)

we made a copy of your form_element_linked_checkbox to create just a linked text element
[teufels/form_element_linked_text](https://bitbucket.org/teufels/form_element_linked_text/src/main/)
but it would be mich more comfortable having it all in one

**Comment by tritum** [comment]
Thanks @bh-teufels for the clarification. We have to think about a possible integration. Will come back to you asap.

**Comment by tritum** [comment]
We have discussed the feature request. We do not want to integrate the linked text solution into the linked checkbox element. There are two reasons:

* 1. One could use static text or a content element to display the information including a link.
* 2. One could use your extension.

Let's keep the focus of this extension. Sorry for closing your feature request.
