### ISSUE TITLE
No %s substitution

### ISSUE THREAD

**Issue by maximaexchen** [tritum/form_element_linked_checkbox#49]
Hi,

I tried with version 3.0.0 and 2.3.0 in a TYPO3 10.4.
In version 3.0.0 %s is not substituted. No link at all
In version 2.3.0 %s is not substitutet and the link ist position at the end of the sentence.

TypoScript is included and no errors on form creation.

Did I miss any configuration steps? Or any configuration which could prevent substitution?

I tried to debug "typo3conf/ext/form_element_linked_checkbox/Classes/Hooks/FormElementLinkResolverHook.php"
I get no dumps out of it.

**Comment by eliashaeussler** [comment]
Hi @maximaexchen, can you show us your `.form.yaml` configuration?

**Comment by maximaexchen** [comment]
Hey @eliashaeussler ,
this is my yaml.

`
renderingOptions:
  submitButtonLabel: versenden
identifier: upload
label: upload
type: Form
prototypeName: standard
finishers:
  -
    options:
      subject: 'Your message: {subject}'
      recipients:
        apo@moon-media.biz: 'Apotheke im Ärztehaus Kitzingen'
      senderAddress: '{email}'
      senderName: '{name}'
      attachUploads: true
      translation:
        language: ''
      useFluidEmail: true
      title: 'Confirmation of your message'
      addHtmlPart: true
    identifier: EmailToReceiver
renderables:
  -
    renderingOptions:
      previousButtonLabel: ''
      nextButtonLabel: ''
    identifier: page-1
    label: 'Contact Form'
    type: Page
    renderables:
      -
        type: GridRow
        identifier: gridrow-1
        label: 'Grid: Zeile'
        renderables:
          -
            properties:
              saveToFileMount: '1:/user_upload/'
              allowedMimeTypes:
                - application/pdf
              gridColumnClassAutoConfiguration:
                viewPorts:
                  lg:
                    numbersOfColumnsToUse: '12'
                  md:
                    numbersOfColumnsToUse: '12'
                  sm:
                    numbersOfColumnsToUse: '12'
                  xs:
                    numbersOfColumnsToUse: '12'
              fluidAdditionalAttributes:
                required: required
            type: FileUpload
            identifier: fileupload-2
            label: Dateiupload
            validators:
              -
                identifier: NotEmpty
          -
            defaultValue: ''
            identifier: name
            label: Name
            type: Text
            properties:
              fluidAdditionalAttributes:
                placeholder: 'Name/Vorname*'
                required: required
              gridColumnClassAutoConfiguration:
                viewPorts:
                  lg:
                    numbersOfColumnsToUse: '12'
                  md:
                    numbersOfColumnsToUse: '12'
                  sm:
                    numbersOfColumnsToUse: '12'
                  xs:
                    numbersOfColumnsToUse: '12'
            validators:
              -
                identifier: NotEmpty
          -
            defaultValue: ''
            identifier: subject
            label: Straße
            type: Text
            properties:
              fluidAdditionalAttributes:
                placeholder: Straße
                required: required
              gridColumnClassAutoConfiguration:
                viewPorts:
                  lg:
                    numbersOfColumnsToUse: '12'
                  md:
                    numbersOfColumnsToUse: '12'
                  sm:
                    numbersOfColumnsToUse: '12'
                  xs:
                    numbersOfColumnsToUse: '12'
            validators:
              -
                identifier: NotEmpty
          -
            defaultValue: ''
            identifier: email
            label: Email
            type: Text
            properties:
              fluidAdditionalAttributes:
                placeholder: 'Email address'
                required: required
              gridColumnClassAutoConfiguration:
                viewPorts:
                  lg:
                    numbersOfColumnsToUse: '12'
                  md:
                    numbersOfColumnsToUse: '12'
                  sm:
                    numbersOfColumnsToUse: '12'
                  xs:
                    numbersOfColumnsToUse: '12'
            validators:
              -
                identifier: NotEmpty
              -
                identifier: EmailAddress
          -
            type: Checkbox
            identifier: checkbox-1
            label: 'Check 01'
            properties:
              elementDescription: 'Check 01'
              gridColumnClassAutoConfiguration:
                viewPorts:
                  lg:
                    numbersOfColumnsToUse: '12'
                  md:
                    numbersOfColumnsToUse: '12'
                  sm:
                    numbersOfColumnsToUse: '12'
                  xs:
                    numbersOfColumnsToUse: '12'
      -
        properties:
          pageUid: '10'
          linkText: Datenschutzerklärung
          fluidAdditionalAttributes:
            required: required
          elementDescription: Datenschutz
        type: LinkedCheckbox
        identifier: linkedcheckbox-1
        label: 'Ich erkläre mich mit der Erhebung, Verarbeitung und Speicherung meiner hier gemachten Angaben gemäß Ihrer %s  einverstanden. Meine Einwilligung kann ich jederzeit durch formlose Mitteilung an Sie widerrufen.'
        validators:
          -
            identifier: NotEmpty
`

**Comment by lukasnetz** [comment]
Hi @maximaexchen your linkText has to be in quotation marks.
`linkText: 'Datenschutzerklärung'`
It should work fine then.
i hope i could help even this late to your issue

**Comment by tritum** [comment]
Has been resolved. Closing this. Thanks mates!
