### ISSUE TITLE
Non unique translation file ID 

### ISSUE THREAD

**Issue by magicsunday** [tritum/form_element_linked_checkbox#52]
Please do not use the ID 20 to specify the translation file, it is better to use the value of a time stamp instead, otherwise there is a risk that the ID will overlap with other form extensions.

https://github.com/tritum/form_element_linked_checkbox/blob/a28dc11be33158c238ea8daaaa1d141e49a25320/Configuration/Yaml/FormSetup.yaml#L78

**Comment by Barakur** [comment]
Additionally set the index for the JS-ViewModel zu a time stamp as well:
```
dynamicRequireJsModules:
  additionalViewModelModules:
	- 'TYPO3/CMS/FormElementLinkedCheckbox/Backend/FormEditor/ViewModel'
```
will conflict with other extensions since the ViewModel ist added to index 0.

Change it to 
```
dynamicRequireJsModules:
  additionalViewModelModules:
	1665989676: 'TYPO3/CMS/FormElementLinkedCheckbox/Backend/FormEditor/ViewModel'
```

**Comment by tritum** [comment]
Will change both of the commented lines in the upcoming v4 release.
