### ISSUE TITLE
Add documentation about "conflict" with form-mailtext

### ISSUE THREAD

**Issue by kpnielsen** [tritum/form_element_linked_checkbox#54]
The extension form-mailtext cannot be used OOTB with this extension due to both overwriting the same templates used by the Email Finishers, see also [this issue](https://github.com/kitzberger/form-mailtext/issues/19). While this can easily be overcome by an integrator by providing their own templates, I propose adding a short paragraph about this little complication in both extensions' READMEs, so that integrators are aware and know the steps they have to take to overcome this.

**Comment by tritum** [comment]
Thanks @kpnielsen. I have improved the README in current master. Will be released with v4.0 soon.
