### ISSUE TITLE
feature: anchor links

### ISSUE THREAD

**Issue by t3brightside** [tritum/form_element_linked_checkbox#55]
Thanks for the great extension!

Would be really useful if links could be not only to pages but content elements as well.
Could then use anchors for opening popups etc or even just link to a certain section of a page.

**Comment by tritum** [comment]
Thanks @t3brightside for your contribution. As stated in #50 the request is to allow more elements to be linked to. This could be content elements or other kind of links (mail, files, additional records configured via linkhandler).

This is quite a change and we have to think about it. To be honest: it is not on our agenda ATM.

**Comment by tritum** [comment]
After some discussions, I am closing this feature request. As of now, EXT:form would need some features in order to provide a solution in our extension. Atm we are working on the roadmap of EXT:form for v13. Will keep this issue in mind while planning.
