### ISSUE TITLE
typo3 9.5.1: ext_emconf.php not valid?

### ISSUE THREAD

**Issue by kueblermedia** [tritum/form_element_linked_checkbox#6]
After Uploading via t3-Backend the files are stored in a doubled folder, moving the folder in the folder one level up, leads to the following error:

Oops, an error occurred!
No valid ext_emconf.php file found for package "form_element_linked_checkbox-master".

**Comment by tritum** [comment]
Please put the extension in the folder "/typo3conf/ext". The extension folder has to be "form_element_linked_checkbox". So the full path would be "/typo3conf/ext/form_element_linked_checkbox".

**Comment by kueblermedia** [comment]
Perfect, that works. ThanksAfter decompression the folder-names ends with "-master". Deleting that and extension is shown in typo3-Backend.
