### ISSUE TITLE
TYPO3 13 Compability

### ISSUE THREAD

**Issue by linawolf** [tritum/form_element_linked_checkbox#73]
What are your plans? Are you welcoming PRs?

**Comment by steffen-hph** [comment]
Hi @linawolf 

i take your version for v13, but in my system the labels are empty in BE. I thought it's a problem with my setup (like https://github.com/tritum/form_element_linked_checkbox/issues/19), but i have the problem also in an empty typo3 only with v13 and this ext. 
Are the labels displayed on your system?

![image](https://github.com/user-attachments/assets/9317f4d4-7e0d-4194-8577-d9c4e69959bd)

**Comment by linawolf** [comment]
Yes, I noted the issue but didnt find a solution yet

**Comment by tritum** [comment]
I will provide a fix for that and tag a stable version today. Thank you for your patience.

**Comment by tritum** [comment]
Released v5.0.0 with TYPO3 v13 compatibility: https://github.com/tritum/form_element_linked_checkbox/releases/tag/v5.0.0
